// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uettsltisucthwhauuuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldHRzbHRpc3VjdGh3aGF1dXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTcwMzYsImV4cCI6MjA3MjQ5MzAzNn0.dl1ToIhYnZtiX8P_yWI9SDVwPkg2MpO0nYmyf4WksHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});